# Generated by Django 3.1.12 on 2026-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=512)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_attachments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmailMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('mailbox_id', models.CharField(db_index=True, max_length=255)),
                ('message_id', models.CharField(max_length=512)),
                ('thread_id', models.CharField(blank=True, max_length=512, null=True)),
                ('subject', models.CharField(default='', max_length=1024)),
                ('from_name', models.CharField(default='', max_length=255)),
                ('from_email', models.CharField(default='', max_length=255)),
                ('to', models.JSONField(default=list)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('preview', models.TextField(default='')),
                ('read', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('labels', models.JSONField(default=list)),
                ('has_attachment', models.BooleanField(default=False)),
                ('priority', models.CharField(default='medium', max_length=32)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('trashed', models.BooleanField(default=False)),
                ('total_chunks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_metadata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=64)),
                ('auto_reminder_sent', models.BooleanField(default=False)),
                ('suggested_action', models.CharField(default='', max_length=512)),
                ('days_waiting', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'follow_ups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('color', models.CharField(default='#0ea5e9', max_length=32)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_secure', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_secure', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255)),
                ('encrypted_password', models.CharField(max_length=1024)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mailboxes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('token', models.CharField(max_length=512)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'refresh_tokens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('daily_briefing', models.BooleanField(default=True)),
                ('slack_digest', models.BooleanField(default=False)),
                ('critical_alerts', models.BooleanField(default=True)),
                ('ai_suggestions', models.BooleanField(default=True)),
                ('auto_labeling', models.BooleanField(default=True)),
                ('thread_summaries', models.BooleanField(default=True)),
                ('sync_range_months', models.IntegerField(default=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_settings',
                'managed': True,
            },
        ),
    ]
